### ISSUE TITLE
频道人数统计问题

### ISSUE THREAD

**Issue by ShadowinFlight** [TateLuo/MorseLink#1]
如果在没有断开连接的情况下关闭软件，自己所在频道的人数不会减一。
具体情况就是，本来我在CH1，人数为1.当我没有点击断开连接直接退出软件，下次再次打开软件连接CH1，人数会直接显示为2

**Comment by ShadowinFlight** [comment]
还有如果当前连接的是CH1，而在CH2点击断开连接，则CH1人数不会减一，而CH2人数减一

**Comment by TateLuo** [comment]
> 如果在没有断开连接的情况下关闭软件，自己所在频道的人数不会减一。 具体情况就是，本来我在CH1，人数为1.当我没有点击断开连接直接退出软件，下次再次打开软件连接CH1，人数会直接显示为2



> 如果在没有断开连接的情况下关闭软件，自己所在频道的人数不会减一。 具体情况就是，本来我在CH1，人数为1.当我没有点击断开连接直接退出软件，下次再次打开软件连接CH1，人数会直接显示为2

这个情况我测试没遇到啊

**Comment by TateLuo** [comment]
> 还有如果当前连接的是CH1，而在CH2点击断开连接，则CH1人数不会减一，而CH2人数减一

这个问题确实存在，下个版本会优化
