### ISSUE TITLE
打开失败

### ISSUE THREAD

**Issue by masterchange13** [TateLuo/MorseLink#2]
![image](https://github.com/user-attachments/assets/296fc945-3732-48e2-bb79-8d5323b8fa90)

**Comment by masterchange13** [comment]
请问如何解决

**Comment by TateLuo** [comment]
方便留下系统版本，声卡硬件型号，驱动版本，以及声道数量作为参考嘛

**Comment by TateLuo** [comment]
跟你的音频外设有关系，如无线耳机或者音响
